name: Node.js CI

on:
  push:
    branches: [ "master", "actions-test" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.18, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run build:prod
      - uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: "${{ secrets.SERVER_SSH_KEY }}"
          REMOTE_HOST: "${{ secrets.SERVER_HOST }}"
          REMOTE_USER: "${{ secrets.SERVER_USER }}"
          SOURCE: "dist"
          TARGET: "/usr/share/nginx/mgs-admin/"
